services:
  - type: web
    name: finance-with-ai-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn services.app.main:app --host 0.0.0.1 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CEREBRAS_API_KEY
        sync: false
      - key: SAMBANOVA_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: INDIANAPI_API_KEY
        sync: false
    autoDeploy: false
